const LOADER_PHRASES = [
  "Cargando canasta de huevos...",
  "Cargando base de datos de unos infelices sobrevalorados...",
  "Buscando el sentido de la vida en Supabase...",
  "Convenciendo a la IA de que trabaje gratis...",
  "Negociando con los servidores... piden cafe...",
  "Despertando al pato que estaba durmiendo...",
  "Traduciendo jeroglificos de LinkedIn...",
  "Haciendo magia negra con los datos...",
  "Preguntandole a ChatGPT si esta bien o esta mal...",
  "Cargando propuestas de gente que no va a responder...",
  "Optimizando el algoritmo de la procrastinacion...",
  "Robando WiFi del vecino para cargar mas rapido...",
  "Buscando developers que cobren barato... imposible...",
  "Contando pixeles uno por uno...",
  "Esperando que el cliente conteste... ja...",
  "Inflando el presupuesto como buen freelancer...",
  "Calculando cuantos cafes necesitas hoy...",
  "Haciendo pair programming con el pato de goma...",
  "Buscando bugs... encontre 47 features...",
  "Cargando el ego de los tech leads...",
  "Compilando excusas para el deadline...",
  "Analizando perfiles de gente mas exitosa que vos...",
  "Generando respuestas que parecen humanas...",
  "Descargando la motivacion del lunes...",
  "Encriptando las lagrimas del sprint review...",
  "Indexando todas las promesas incumplidas...",
  "Cacheando las mentiras del curriculum...",
  "Parseando el dolor de los freelancers...",
  "Bootstrapping la ansiedad del emprendedor...",
  "Deploy en produccion un viernes... que podria salir mal...",
  "Buscando el product-market fit en el baño...",
  "Cargando la paciencia... error 404...",
  "Sincronizando relojes con la realidad...",
  "Alimentando a los hamsters que corren los servers...",
  "Refactorizando la vida personal... todo es legacy...",
  "Scrapeando la felicidad de internet...",
  "Entrenando al modelo con memes de programacion...",
  "Buscando inversores... encontre cucarachas...",
  "Cargando la base de datos de arrepentimientos...",
  "Ejecutando npm install de la existencia...",
  "Esperando el pull request de la suerte...",
  "Haciendo merge de los problemas de ayer con los de hoy...",
  "Resolviendo conflictos... no de git, de la vida...",
  "Debuggeando por que nadie contesta en Workana...",
  "Consultando el oraculo de Stack Overflow...",
  "Migrating from sueños to realidad...",
  "Cargando el cinismo profesional...",
  "Warming up las excusas del daily...",
  "Fetching motivacion... timeout after 30s...",
  "Spinning up los contenedores de la esperanza...",
];

export function getRandomPhrase(): string {
  return LOADER_PHRASES[Math.floor(Math.random() * LOADER_PHRASES.length)];
}

export default LOADER_PHRASES;
